### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by rotamota** [sleemanj/gogoTradeMe#1]
Fatal error: Uncaught exception 'Exception' with message 'Unknown data format: ' in C:\wamp\www\trademe\lib\gogoOAuth\gogoOAuthResponse.php:246 Stack trace: #0 C:\wamp\www\trademe\lib\gogoOAuth\gogoOAuthResponse.php(230): gogoOAuthResponse->data() #1 [internal function]: gogoOAuthResponse->__call('to_array', Array) #2 C:\wamp\www\trademe\lib\gogoOAuth\gogoOAuth.php(119): gogoTradeMeResponse->to_array() #3 C:\wamp\www\trademe\example\connect.php(16): gogoOAuth->get_request_token() #4 {main} thrown in C:\wamp\www\trademe\lib\gogoOAuth\gogoOAuthResponse.php on line 246

Any ideas?

Thanks heaps.

**Comment by bwash70** [comment]
Hey mate... hoping to get this to work for a property site I'm building for myself.

I've added the example and lib directories to my website (www.simplr.it/property/).

When going to /example/index.php and hitting connect then Begin Authorisation I get the response: 

Warning: require_once(/lib/gogoTradeMe/gogoTradeMeSandbox.php): failed to open stream: No such file or directory in /home/content/75/10390475/html/property/example/include/init.php on line 21

Fatal error: require_once(): Failed opening required '/lib/gogoTradeMe/gogoTradeMeSandbox.php' (include_path='.:/usr/local/php5_4/lib/php') in /home/content/75/10390475/html/property/example/include/init.php on line 21

Any chance you could help would be great...

Thank you
Ben

**Comment by sleemanj** [comment]
You must have a problem in your PHP include path/configuration, or you
have modified the paths in init.php incorrectly. 

I direct you to the PHP documentation: 

 http://php.net/require_once 

 http://php.net/require 

 http://php.net/include

**Comment by bwash70** [comment]
Hey - I'm using require_once in other pages on my site which are working OK.

After adding speech marks around the consumer key/secret in the config.php file I'm now getting:

Warning: require_once(/home/content/75/10390475/html/property/lib/gogoTradeMe/../gogoOAuth/gogoOAuth.php): failed to open stream: No such file or directory in /home/content/75/10390475/html/property/lib/gogoTradeMe/gogoTradeMe.php on line 26

Fatal error: require_once(): Failed opening required '/home/content/75/10390475/html/property/lib/gogoTradeMe/../gogoOAuth/gogoOAuth.php' (include_path='.:/usr/local/php5_4/lib/php') in /home/content/75/10390475/html/property/lib/gogoTradeMe/gogoTradeMe.php on line 26

I haven't modified any files other than the config.php - am I missing something? Do you want me to post some code?

Thanks again

**Comment by sleemanj** [comment]
You have not retrieved the git submodule lib/gogoOAuth 

Please read at least the first post here: 

https://web.archive.org/web/20150114234323/http://developer.trademe.co.nz/forum/?mingleforumaction=viewtopic&t=118.0

**Comment by bwash70** [comment]
Thank you... all working.

Appreciate your help - and putting this together!
